In [6]:
import numpy as np

# Creating NumPy arrays

In [7]:
def test_run():
    print(np.array([2,3,4])) #list of 1D array
    print(np.array([(2,3,4), (5,6,7)])) #list of tuples to 2D array

if __name__ == "__main__":
    test_run()

[2 3 4]
[[2 3 4]
 [5 6 7]]


# Creating arrays with initial values

In [8]:
def test_run():
    print(np.empty(5)) #empty array with shape of 5
    print(np.empty((5,4))) #empty array with 5 rows and 4 columns
    print(np.empty((5,4,3))) #empty array with depth of 3 and each has 5 rows and 4 columns
    
if __name__ == "__main__":
    test_run()

[1.38338381e-322 6.92226963e-310 4.94065646e-324 0.00000000e+000
 6.36598738e-314]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[[ 6.92226943e-310  6.92226943e-310  0.00000000e+000]
  [ 0.00000000e+000  6.01334668e-154  4.47590761e-091]
  [ 6.01347002e-154  1.81363716e-152  1.10638849e+200]
  [ 3.09076222e+169  1.06113401e-153  2.32066100e-152]]

 [[ 7.87488138e+276  2.45066340e+198  5.98181661e-154]
  [ 1.46914166e+195  9.06756708e+271  1.10638851e+200]
  [ 4.19334284e+228  1.81364819e-152  3.17095864e+180]
  [ 1.11789363e+253  5.83553021e+252  6.01346953e-154]]

 [[ 1.68044185e+241  5.07623833e-310  1.63002224e-070]
  [ 1.65889757e+166  6.48120960e-304  1.33360460e+241]
  [ 1.83853959e-309  1.88743680e+007  1.40996673e-312]
  [ 1.14448622e+243  2.41695321e-311  2.67403555e+246]]

 [[ 6.36699571e+151  8.19148733e+247  1.11083159e+171]
  [ 1.97626258e-323  1.27319747e-313  1.00221861e-310]
  [ 2.12988483e+289 -5.26054259e-246  3.17898110e-292]
  [ 6.0134

In [9]:
def test_run():
    print(np.ones((5,4))) #array of ones with 5 rows and 4 columns
    print(np.zeros((5,4))) #array of zeros with 5 rows and 4 columns
    
if __name__ == "__main__":
    test_run()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Generating random numbers

In [22]:
print(np.random.random((5,4))) #random numbers in tuple of 5 rows and 4 columns.
#Floating numbers are generated between 0 and 1.

print(np.random.normal(size=(2,3))) #numbers from normal (Gaussian) distribution, i.e. mean = 0, std = 1

print(np.random.normal(50, 10, size=(2,3))) #50 is mean, std is 10

[[0.89875425 0.07399542 0.54025136 0.43539804]
 [0.0095113  0.6453064  0.17899681 0.04476179]
 [0.52843273 0.84037582 0.16695932 0.67984082]
 [0.13093942 0.62514735 0.1840197  0.56762275]
 [0.44472974 0.61282002 0.51954164 0.10323785]]
[[-0.20960172  0.07421705  0.80769137]
 [ 0.8833386   1.0135087   1.85921737]]
[[37.37875338 61.27703224 39.1926896 ]
 [61.47134125 41.30834505 56.36899373]]


In [29]:
print(np.random.randint(10)) #a single integer in [0,10]
print(np.random.randint(0, 10)) #a single integer in [0,10], but specifying low and high explicitly
print(np.random.randint(0, 10, size=(5))) #5 integers as 1D array
print(np.random.randint(0, 10, size=(4,5))) #5 integers as an array with 4 rows and 5 columns

5
0
[6 7 2 5 9]
[[2 5 1 4 0]
 [4 6 9 1 1]
 [6 6 1 2 4]
 [4 1 1 6 3]]


# Array attributes

In [41]:
a = np.random.random((3,2))
print(a)
print(a.shape)
print(a.shape[0]) #returns the number of rows
print(a.shape[1]) #returns the number of columns
print(len(a.shape)) #returns a dimension of the array
print(a.size) #returns the number of elements in the array, i.e. rows * columns
print(a.dtype) #retur

[[0.32206669 0.58519325]
 [0.62104715 0.71944616]
 [0.15666915 0.04056733]]
(3, 2)
3
2
2
6
float64
