In [8]:
import numpy as np

# Creating NumPy arrays

In [9]:
def test_run():
    print(np.array([2,3,4])) #list of 1D array
    print(np.array([(2,3,4), (5,6,7)])) #list of tuples to 2D array

if __name__ == "__main__":
    test_run()

[2 3 4]
[[2 3 4]
 [5 6 7]]


# Creating arrays with initial values

In [15]:
def test_run():
    print(np.empty(5)) #empty array with shape of 5
    print(np.empty((5,4))) #empty array with 5 rows and 4 columns
    print(np.empty((5,4,3))) #empty array with depth of 3 and each has 5 rows and 4 columns
    
if __name__ == "__main__":
    test_run()

[0.00e+000 4.94e-324 0.00e+000 0.00e+000 3.95e-322]
[[[0.00000000e+000 4.98833020e+098 4.63919623e-310]
  [4.63919623e-310 4.63919623e-310 8.48798317e-314]
  [6.01346930e-154 4.63919623e-310 4.63919623e-310]
  [4.63919623e-310 0.00000000e+000 0.00000000e+000]]

 [[8.48798317e-314 0.00000000e+000 0.00000000e+000]
  [4.94065646e-324 6.91889363e-310 4.63919623e-310]
  [4.63919623e-310 4.63919623e-310 0.00000000e+000]
  [4.94065646e-324 9.89803212e+164 4.63919623e-310]]

 [[1.69724916e+137 1.61410559e+132 6.36598738e-314]
  [1.42137819e-076 4.63919623e-310 4.63919623e-310]
  [4.63919623e-310 6.36598738e-314 4.94065646e-324]
  [4.63919623e-310 1.69724916e+137 6.91889363e-310]]

 [[9.89803212e+164 9.16281387e-072 8.48798317e-314]
  [9.45956165e-076 4.63919623e-310 0.00000000e+000]
  [0.00000000e+000 8.48798317e-314 2.95149494e-075]
  [4.63919623e-310 6.60925411e-062 9.16281386e-072]]

 [[1.42137876e-076 1.11416848e+218 8.48798317e-314]
  [9.89803212e+164 4.63919623e-310 4.63919623e-310]
  [0

In [18]:
def test_run():
    print(np.ones((5,4))) #array of ones with 5 rows and 4 columns
    print(np.zeros((5,4))) #array of zeros with 5 rows and 4 columns
    
if __name__ == "__main__":
    test_run()

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Generating random numbers